server:
  port: 8080
vue:
  address: http://localhost:5173,http://192.168.6.103:5173
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
pay-server: localhost
protocol: http


nginx:
  static-server:
    ssh:
      username: sftp_static_server
      password: 123456
      host: localhost
      port: 22
      path: /sftp_static_server/static


debug: true
logging:
  level:
    com.lyu.controller: debug
    com.lyu.com.lyu.service: debug